name: "Build Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  get_tags:
    runs-on: ubuntu-22.04
    outputs:
        value: ${{steps.get_tags.outputs.latest_tag}}

    steps:
      - name: Checkout Tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: "get_tags"
        run: |
          LATEST_TAG=$(git tag --sort=taggerdate | tail -1)
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

  build:
    needs: get_tags
    runs-on: ubuntu-22.04
    steps:
      - run: echo tag [${{needs.get_tags.outputs.latest_tag}}]

