name: "Build Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build_type:
    runs-on: ubuntu-22.04
    outputs:
      value: ${{steps.build-type.outputs.value}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Build Type"
        id: "build-type"
        run: |
          BUILD_TYPE="NONE"
          LATEST_TAG=$(git tag --sort=taggerdate | tail -1)

          if [[ -z $LATEST_TAG ]]; then
            BUILD_TYPE="FULL"
          else
            CHANGES=$(git diff --name-only -r $LATEST_TAG HEAD | xargs)
            for file in $CHANGES; do
              echo "$file was changed"
            done
          fi
          
          echo "value=$BUILD_TYPE" >> $GITHUB_OUTPUT
  
  full_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "Full Build"
        if: ${{needs.build_type.outputs.value == 'FULL'}}
        run: echo "Full Build"

  part_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "Part Build"
        if: ${{needs.build_type.outputs.value == 'PART'}}
        run: echo "Part Build"


  none_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "None Build"
        if: ${{needs.build_type.outputs.value == 'NONE'}}
        run: echo "Build Not Needed"
