name: "Build Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  builder:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $LATEST_TAG
