name: "Build Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  latest_tag:
    runs-on: ubuntu-22.04
    outputs:
        value: ${{steps.get_tag.outputs.value}}

    steps:
      - name: Checkout Tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: "get_tag"
        run: |
          LATEST_TAG=$(git tag --sort=taggerdate | tail -1)
          echo $LATEST_TAG
          echo "value"=$LATEST_TAG" >> $GITHUB_OUTPUT

  build:
    needs: latest_tag
    runs-on: ubuntu-22.04
    steps:
      - run: echo tag [${{needs.latest_tag.outputs.value}}]

