name: "Build Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  latest_tag:
    runs-on: ubuntu-22.04
    outputs:
        value: ${{steps.get-tag.outputs.value}}
    steps:
      - name: "Checkout Tags"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: "Get Latest Tag"
        id: "get-tag"
        run: |
          LATEST_TAG=$(git tag --sort=taggerdate | tail -1)
          echo "value=$LATEST_TAG" >> $GITHUB_OUTPUT

  build_type:
    needs: latest_tag
    runs-on: ubuntu-22.04
    outputs:
      value: ${{steps.build-type.outputs.value}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Build Type"
        id: "build-type"
        run: |
          CHNAGES=$(git diff --name-only -r ${{needs.latest_tag.outputs.value}} HEAD | xargs)
          for file in $CHANGES; do
            echo "$file was changed"
          done

          BUILD_TYPE="NONE"
          echo "value=$BUILD_TYPE" >> $GITHUB_OUTPUT
  
  full_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "Full Build"
        if: ${{needs.build_type.outputs.value == "FULL"}}
        run: echo "Full Build"

  part_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "Part Build"
        if: ${{needs.build_type.outputs.value == "PART"}}
        run: echo "Part Build"


  none_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "None Build"
        if: ${{needs.build_type.outputs.value == "NONE"}}
        run: echo "Build Not Needed"
