name: "Build Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  new_build_type:
    runs-on: ubuntu-22.04
    outputs:
      value: ${{steps.build-type.outputs.value}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Latest Tag"
        id: "latest-tag"
        run: |
          LATEST_TAG=$(git tag --sort=taggerdate | tail -1)
          echo "value=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: "Changed Files"
        if: ${{steps.latest-tag.outputs.value != ''}}
        id: "changed-files"
        uses: tj-actions/changed-files@v44
        with:
          base_sha: HEAD
          sha: ${{steps.latest-tag.outputs.value}}

      - name: "List Files"
        env:
          ALL_CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files}}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  build_type:
    runs-on: ubuntu-22.04
    outputs:
      value: ${{steps.build-type.outputs.value}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Latest Tag"
        id: "latest-tag"
        run: |
          LATEST_TAG=$(git tag --sort=taggerdate | tail -1)
          echo "value=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: "Changed Files"
        if: ${{steps.latest-tag.outputs.value != ''}}
        id: "changed-files"
        uses: tj-actions/changed-files@v44
        with:
          base_sha: HEAD
          sha: ${{steps.latest-tag.outputs.value}}
          files_yaml: |
            full:
              - buildAll.txt
            part:
              - buildPartial.txt

      - name: "Build Type"
        id: "build-type"
        run: |
          BUILD_TYPE="NONE"
          if [[ ${{steps.latest-tag.outputs.value}} == '' ]]; then
            echo No Tag
            BUILD_TYPE="FULL"
          elif [[ ${{steps.changed-files.outputs.full_any_changed}} == 'true' ]]; then
            echo Full
            BUILD_TYPE="FULL"
          elif [[ ${{steps.changed-files.outputs.part_any_changed}} == 'true' ]]; then
            echo Partial
            BUILD_TYPE="PART"
          fi
          echo $BUILD_TYPE
          echo "value=$BUILD_TYPE" >> $GITHUB_OUTPUT

  full_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "Full Build"
        if: ${{needs.build_type.outputs.value == 'FULL'}}
        run: echo "Full Build"

  part_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "Part Build"
        if: ${{needs.build_type.outputs.value == 'PART'}}
        run: echo "Part Build"


  none_build:
    needs: build_type
    runs-on: ubuntu-22.04

    steps:
      - name: "None Build"
        if: ${{needs.build_type.outputs.value == 'NONE'}}
        run: echo "Build Not Needed"
