name: Full Docker Build

on:
  workflow_call:

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outputs.success }}
    steps:
      - name: Build
        id: build
        run: |
          success='true'
          echo "success=$success" >> $GITHUB_OUTPUT
