name: Incremental Docker Build

on:
  workflow_call:
    outputs:
      success:
        description: Success Status of Build
        value: ${{ jobs.update.outputs.success }}

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.update.outputs.success }}
    steps:
      - name: Update
        id: update
        run: |
          success='true'
          echo "success=$success" >> $GITHUB_OUTPUT
