name: Full Docker Build

on:
  workflow_call:
    outputs:
      success:
        description: Success Status of Build
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    name: Rebuild
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outputs.success }}
    steps:
      - name: Build
        id: build
        run: |
          success='true'
          echo "success=$success" >> $GITHUB_OUTPUT
